# Generated by Django 3.1.7 on 2021-03-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('targy', models.CharField(max_length=128)),
                ('db', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Elem',
                'verbose_name_plural': 'Elemek',
            },
        ),
    ]
