# Generated by Django 3.1.7 on 2021-03-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevasarlolistaapp', '0004_auto_20210302_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bevasarlolista',
            name='nev',
            field=models.CharField(default='Névtelen', max_length=30),
        ),
        migrations.AlterField(
            model_name='bevasarlolista',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
