# Generated by Django 3.1.7 on 2021-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevasarlolistaapp', '0005_auto_20210302_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bevasarlolista',
            name='nev',
            field=models.CharField(default='2021.03.03', max_length=30),
        ),
    ]
